items:
  - colors:
      name: 3024 (dark)
      author: Chris Kempson
      primary:
        background: "#1D1F21"
        foreground: "#a5a2a2"
      cursor:
        text: "#090300"
        cursor: "#a5a2a2"
      normal:
        black: "#090300"
        red: "#db2d20"
        green: "#01a252"
        yellow: "#fded02"
        blue: "#01a0e4"
        magenta: "#a16a94"
        cyan: "#b5e4f4"
        white: "#a5a2a2"
      bright:
        black: "#5c5855"
        red: "#db2d20"
        green: "#01a252"
        yellow: "#fded02"
        blue: "#01a0e4"
        magenta: "#a16a94"
        cyan: "#b5e4f4"
        white: "#f7f7f7"
  - theme: 3024.dark
colors:
  # Default colors
  primary:
    background: '#1D1F21'
    foreground: '#d6d6d6'

    dim_foreground: '#dbdbdb'
    bright_foreground: '#d9d9d9'
    dim_background: '#202020' # not sure
    bright_background: '#3a3a3a' # not sure

  # Cursor colors
  cursor:
    text: '#2c2c2c'
    cursor: '#d9d9d9'

  # Normal colors
  normal:
    black: '#000000'
    red: '#bc5653'
    green: '#909d63'
    yellow: '#ebc17a'
    blue: '#01a0e4'
    magenta: '#aa6292'
    cyan: '#86d3ce'
    white: '#cacaca'

  # Bright colors
  bright:
    black: '#636363'
    red: '#bc5653'
    green: '#909d63'
    yellow: '#ebc17a'
    blue: '#7eaac7'
    magenta: '#aa6292'
    cyan: '#86d3ce'
    white: '#f7f7f7'

  # Dim colors
  dim:
    black: '#232323'
    red: '#74423f'
    green: '#5e6547'
    yellow: '#8b7653'
    blue: '#556b79'
    magenta: '#6e4962'
    cyan: '#5c8482'
    white: '#828282'
theme: Afterglow
