format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

right_format = "$time"
command_timeout = 10_000
scan_timeout = 1_000

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 3
format = "[$path]($style)[$lock_symbol]($lock_style) "

[character]
success_symbol = "[❯](yellow)"
error_symbol = "[❯](red)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[\\[($conflicted$untracked$modified$staged$renamed$deleted)\\]](purple) ($ahead_behind$stashed)]($style)"
style = "cyan"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style)"
style = "green"

[time]
disabled = false
style = "bright-black"
format = "[$time]($style)"
time_format = "%T"
