-- LazyVim loads the colourscheme these dotfiles carry, in colors/dotfiles.lua.
--
-- No plugin: that file is generated by scripts/theme.sh from the same palette
-- every other program here is themed from, and neovim finds it on its own.
return {
  { "LazyVim/LazyVim", opts = { colorscheme = "dotfiles" } },
}
