icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = ""

[icons]
icons = "material-nf"

[[block]]
block = "cpu"
interval = 5
format = "$icon $utilization "
format_alt = "$icon $frequency{ $boost|} $barchart "

[[block]]
block = "memory"
format = "$icon $mem_used_percents.eng(w:1)"
format_alt = "$icon_swap $mem_total_used.eng(w:3,u:B,p:Mi)/($mem_total_used_percents.eng(w:2))"


[[block]]
block = "temperature"
interval = 5
chip = "thinkpad-isa-0000"
inputs = ["CPU"]
format = " $icon $min"
[block.theme_overrides]
info_bg = { link = "idle_bg"}

[[block]]
block = "keyboard_layout"
driver = "kbddbus"
format = " $layout "

[[block]]
block = "net"
format = "$icon {$signal_strength $ssid |Wired connection}"

[[block]]
block = "battery"
driver = "upower"
format = " $icon $percentage"
not_charging_format = " $icon $percentage"
[block.theme_overrides]
good_bg = { link = "idle_bg"}
good_fg = { link = "idle_fg"}

[[block]]
block = "backlight"

[[block]]
block = "sound"
headphones_indicator = true
max_vol = 100
format = "$icon {$volume.eng(w:2)|}"

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%R %a %d. %b') "

[[block]]
block = "pomodoro"
format = "$icon  {$message|}"
notify_cmd = "notify-send '{msg}'"
blocking_cmd = false

